server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
mybatis:
  configuration:
    map-underscore-to-camel-case: true
spring:
  mail:
    host: smtp.qq.com #SMTP\u670D\u52A1\u5668\u5730\u5740,163\u90AE\u7BB1\u4F7F\u7528smtp.163.com
    username:  1989414476@qq.com #\u767B\u9646\u8D26\u53F7
    password: amlyjagftggjgggb #\u767B\u9646\u5BC6\u7801\uFF08\u6216\u6388\u6743\u7801\uFF09
  servlet:
    multipart:
      max-file-size: 10MB #\u9650\u5236\u5355\u4E2A\u6587\u4EF6\u5927\u5C0F
      max-request-size: 50MB #\u9650\u5236\u8BF7\u6C42\u603B\u91CF
  application:
    name: service-function
  #\u5F53\u9047\u5230\u540C\u6837\u540D\u5B57\u7684\u65F6\u5019\uFF0C\u662F\u5426\u5141\u8BB8\u8986\u76D6\u6CE8\u518C
  main:
    allow-bean-definition-overriding: true
  datasource:
    #JDBC\u57FA\u672C\u914D\u7F6E
      url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    #\u8FDE\u63A5\u6C60\u7C7B\u578B\u4EE5\u53CA\u76F8\u5173\u914D\u7F6E
    #  Druid\u529F\u80FD\u6700\u597D\uFF0C\u8D44\u6599\u8F83\u591A
      type: com.alibaba.druid.pool.DruidDataSource
# \u8BBE\u7F6E\u65F6\u95F4\u683C\u5F0F
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss



