server:
  port: 9099

spring:
  application:
    name: server-feign-interface

eureka:
  client:
    service-url:
      defaultZone: http://eureka8881:8881/eureka,http://eureka8882:8882/eureka,http://localhost:8880/eureka
